const jokes = [
  "Why did the tomato turn red?Because it saw the salad dressing.",
  "What do you call a fake noodle? An impasta.",
  "What do you call an alligator in a vest? An investigator.",
  "Why don't scientists trust atoms? Because they make up everything.",
  "What's the difference between a poorly dressed man on a trampoline and a well-dressed man on a trampoline? Attire.",
  "Why don't scientists trust atoms? Because they make up everything.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "What do you call a bear with no teeth? A gummy bear.",
  "Why did the bicycle fall over? Because it was two-tired.",
  "Why did the coffee file a police report? It got mugged.",
  "Why was the math book sad? Because it had too many problems.",
  "Why do birds fly south for the winter? Because it's too far to walk.",
  "What do you call a sleeping bull? A bulldozer.",
  "Why don't scientists trust atoms? Because they make up everything.",
  "Why did the chicken cross the playground? To get to the other slide.",
  "Why was the broom late? It swept in.",
  "What do you get when you cross a snowman and a shark? Frostbite.",
  "Why did the cookie go to the doctor? Because it was feeling crumbly.",
  "What do you get when you cross a snowman and a bulldozer? Snow plow.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "What do you call a bear with no teeth? A gummy bear.",
  "Why don't ants get sick? Because they have tiny ant-bodies.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "Why did the bicycle fall over? Because it was two-tired.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "What did the janitor say when he jumped out of the closet? 'Supplies!'",
  "What do you call a snowman with a six-pack? An abdominal snowman.",
  "Why did the banana go to the doctor? Because it wasn't peeling well.",
  "Why don't scientists trust atoms? Because they make up everything.",
  "What do you call an alligator wearing a vest? An investigator.",
  "Why do seagulls fly over the sea? Because if they flew over the bay, they'd be bagels.",
  "Why did the coffee file a police report? It got mugged.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "What's orange and sounds like a parrot? A carrot.",
  "Why was the math book sad? Because it had too many problems.",
  "What do you call a sheep that is always quiet? A ewe-nique.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "Why don't ants get sick? Because they have tiny ant-bodies.",
  "Why do bees hum? Because they don't know the words.",
  "Why was the computer cold? It left its Windows open.",
  "Why did the frog call his insurance company? He had a jump in his car.",
  "Why don't oysters give to charity? They're shellfish.",
  "Why was the belt sent to jail?Because it held up a pair of pants and charged with battery.",
  "Why don't scientists trust atoms? Because they make up everything.",
  "Why was the math book sad? Because it had too many problems.",
  "What do you call a snowman with a six-pack? An abdominal snowman.",
  "Why did the banana go to the doctor? Because it wasn't peeling well.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "Why did the bicycle fall over? Because it was two-tired.",
  "What did the janitor say when he jumped out of the closet? 'Supplies!'",
  "Why do seagulls fly over the sea? Because if they flew over the bay, they'd be bagels.",
  "Why was the computer cold? It left its Windows open.."
];
let Ran_joke = Math.floor(Math.random() * jokes.length);

const random_joke = () => {
document.getElementById("newJoke").innerHTML = jokes[Ran_joke];
}


